import {Fragment,useEffect,useMemo,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {PageHeader} from '../../components/PageHeader';
import {buildCatalogReviewRows,PAGE_SIZE,unsupportedReasonDescription,type CatalogReviewRow} from '../../domain/catalog-review';
import {getCatalogItemStatusCounts,type CatalogRecord} from '../../domain/catalog';
import {catalogsRepository} from '../../storage/catalogs-repository';

type Filter='problems'|'needs_review'|'unsupported'|'invalid'|'validated'|'all';
const json=(value:unknown)=>JSON.stringify(value,null,2);
function value(value:unknown){return value===undefined||value===null?'—':typeof value==='string'?value:json(value)}

function Reasons({row}:{row:CatalogReviewRow}){return <div className="review-reasons">
  {row.status==='unsupported'&&<><h4>Не поддерживается текущей taxonomy</h4><p><code>{row.unsupportedReasonCode}</code> — {unsupportedReasonDescription(row.unsupportedReasonCode)}</p></>}
  {!!row.unknownFields.length&&<section><h4>Не определено</h4><ul>{row.unknownFields.map(pointer=><li key={pointer}><code>{pointer}</code></li>)}</ul></section>}
  {!!row.issues.length&&<section><h4>Issues</h4>{row.issues.map((issue,index)=><div key={`${issue.code}-${index}`}><b>{issue.code}</b>{issue.json_pointer&&<> · <code>{issue.json_pointer}</code></>}{issue.message&&<p>{issue.message}</p>}{issue.details!==undefined&&<pre>{json(issue.details)}</pre>}</div>)}</section>}
  {!!row.ambiguities.length&&<section><h4>Ambiguities</h4>{row.ambiguities.map((a,index)=><div key={`${a.code}-${index}`}><b>{a.code}</b>{a.json_pointer&&<> · <code>{a.json_pointer}</code></>}<p>{a.source_text}{a.possible_values&&<> · Возможные значения: {value(a.possible_values)}</>}{a.blocking!==undefined&&<> · blocking: {String(a.blocking)}</>}</p></div>)}</section>}
  {row.status==='validated'&&<p>Разметка подтверждена.</p>}
</div>}

function Evidence({row}:{row:CatalogReviewRow}){if(!row.evidence.length)return null;return <section><h4>Подтверждено источником</h4><ul>{row.evidence.map((e,index)=><li key={`${e.json_pointer}-${index}`}><code>{e.json_pointer}</code> ← {e.source_text}{e.raw_value!==undefined&&<> · raw: {value(e.raw_value)}</>}{e.source_position&&<> · {e.source_position.sheet}, строка {e.source_position.row}</>}</li>)}</ul></section>}

function ReviewCard({row}:{row:CatalogReviewRow}){const[open,setOpen]=useState(false),position=[row.sourcePosition?.sheet&&`Лист «${row.sourcePosition.sheet}»`,row.sourcePosition?.row&&`строка ${row.sourcePosition.row}`].filter(Boolean).join(', ');return <article className="card review-row" data-status={row.status}>
  <div className="row"><div><h3>{row.rawName}</h3><p>{row.supplierSku&&<>Арт. {row.supplierSku} · </>}{position}{row.classId&&<> · <code>{row.classId}</code></>}</p></div><b>{row.status}</b></div>
  <Reasons row={row}/><button className="link-button" aria-expanded={open} onClick={()=>setOpen(x=>!x)}>{open?'Скрыть':`Подробнее: ${row.rawName}`}</button>
  {open&&<div className="review-detail"><section><h3>Исходная строка</h3><dl className="details">{(['raw_name','supplier_sku','gtin','price','currency','stock_quantity','unit','context','source_position'] as const).map(key=><Fragment key={key}><dt>{key}</dt><dd>{value(row.source[key])}</dd></Fragment>)}</dl><h4>raw_fields</h4><pre>{json(row.source.raw_fields??{})}</pre></section>
  <section><h3>Разметка</h3><p>source_item_id: <code>{row.sourceItemId}</code></p><p>class_id: <code>{row.classId??'—'}</code></p><h4>Identity</h4><pre>{json(row.item.identity??{})}</pre><h4>Атрибуты</h4><pre>{json(row.item.attributes??{})}</pre><h4>Порты</h4><pre>{json(row.item.ports??[])}</pre><Reasons row={row}/><Evidence row={row}/><details><summary>Технические данные</summary><pre>{json(row.item.annotation??{})}</pre></details></section></div>}
  </article>}

export function CatalogReviewPage(){const{recordId}=useParams(),[record,setRecord]=useState<CatalogRecord|null|undefined>(),[filter,setFilter]=useState<Filter>('problems'),[query,setQuery]=useState(''),[page,setPage]=useState(0);useEffect(()=>{catalogsRepository.get(recordId??'').then(value=>setRecord(value??null))},[recordId]);const rows=useMemo(()=>record?buildCatalogReviewRows(record.bundle):[],[record]);const counts=record?getCatalogItemStatusCounts(record.bundle):null;const filtered=useMemo(()=>{const needle=query.toLocaleLowerCase();return rows.filter(row=>(filter==='all'||filter==='problems'&&row.status!=='validated'||row.status===filter)&&(!needle||[row.rawName,row.supplierSku,row.sourceItemId,row.classId].some(x=>x?.toLocaleLowerCase().includes(needle))))},[rows,filter,query]);useEffect(()=>setPage(0),[filter,query]);
  if(record===undefined)return <p role="status">Загрузка каталога…</p>;if(record===null)return <><PageHeader title="Каталог не найден"/><Link to="/catalogs">Вернуться к каталогам</Link></>;
  const filters:Array<[Filter,string,number]>=[['problems','Проблемные',(counts?.needsReview??0)+(counts?.unsupported??0)+(counts?.invalid??0)],['needs_review','Требуют проверки',counts?.needsReview??0],['unsupported','Не поддерживаются',counts?.unsupported??0],['invalid','Invalid',counts?.invalid??0],['validated','Validated',counts?.validated??0],['all','Все',counts?.total??0]];const slice=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE),start=filtered.length?page*PAGE_SIZE+1:0,end=Math.min((page+1)*PAGE_SIZE,filtered.length);
  return <><Link to="/catalogs">← Каталоги</Link><PageHeader title={`Каталог: ${record.catalogId}`} description={`${record.sourceFileName} · taxonomy ${record.taxonomyVersion} · ${counts?.total} позиций`}/><div className="metrics"><strong>{counts?.validated}<small>validated</small></strong><strong>{counts?.needsReview}<small>needs_review</small></strong><strong>{counts?.unsupported}<small>unsupported</small></strong><strong>{counts?.invalid}<small>invalid</small></strong></div>
  <nav className="review-filters" aria-label="Фильтр статуса">{filters.map(([id,label,count])=><button key={id} className={filter===id?'button':'button button--secondary'} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label} {count}</button>)}</nav><label>Поиск по товару<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, артикул, source_item_id или class_id"/></label>
  {!filters[0][2]&&filter==='problems'?<p className="notice">Все позиции каталога validated.</p>:!filtered.length?<p className="notice">{query?'По вашему запросу ничего не найдено.':filter==='unsupported'?'В этом каталоге нет unsupported позиций.':'Нет позиций для выбранного фильтра.'}</p>:<><p>Показано {start}–{end} из {filtered.length}</p>{slice.map(row=><ReviewCard key={row.sourceItemId||`${row.rawName}-${row.sourcePosition?.row}`} row={row}/>)}<div className="actions"><button className="button button--secondary" disabled={!page} onClick={()=>setPage(x=>x-1)}>Назад</button><button className="button button--secondary" disabled={end>=filtered.length} onClick={()=>setPage(x=>x+1)}>Далее</button></div></>}</>}
