import {useEffect,useMemo,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {PageHeader} from '../../components/PageHeader';
import {buildCatalogReviewRows,PAGE_SIZE,unsupportedReasonDescription,type CatalogReviewRow} from '../../domain/catalog-review';
import {getCatalogItemStatusCounts,type CatalogRecord} from '../../domain/catalog';
import {buildCatalogEditFields,type CatalogEditField} from '../../domain/catalog-review-fields';
import {applyCatalogReviewEdits,type CatalogManualEdit} from '../../domain/catalog-review-edit';
import {catalogsRepository,CatalogRevisionChangedError} from '../../storage/catalogs-repository';
import {fieldLabel,valueLabel} from './catalog-review-presentation';

type Filter='needs_review'|'unsupported'|'invalid'|'validated'|'all';
const json=(value:unknown)=>JSON.stringify(value,null,2);
const show=(value:unknown)=>value===undefined||value===null?'—':typeof value==='string'?value:json(value);
function TechnicalDetails({row}:{row:CatalogReviewRow}){return <details><summary>Технические подробности</summary><p>source_item_id: <code>{row.sourceItemId}</code> · class_id: <code>{row.classId??'—'}</code></p><h4>unknown_fields / issues / ambiguities</h4><pre>{json({unknown_fields:row.unknownFields,issues:row.issues,ambiguities:row.ambiguities})}</pre><h4>evidence / operator_confirmations</h4><pre>{json({evidence:row.evidence,operator_confirmations:row.item.annotation?.operator_confirmations??[]})}</pre><h4>identity / attributes / ports</h4><pre>{json({identity:row.item.identity,attributes:row.item.attributes,ports:row.item.ports})}</pre><h4>raw_fields</h4><pre>{json(row.source.raw_fields??{})}</pre></details>}
function FieldEditor({field,value,onChange,error}:{field:CatalogEditField;value:unknown;onChange:(value:unknown)=>void;error?:string}){const label=fieldLabel(field);return <div className="review-field"><label><strong>{label}</strong>{field.kind==='enum'?<select aria-label={label} value={value===undefined?'':String(value)} onChange={e=>onChange(e.target.value)}><option value="">Выберите значение</option>{field.options?.map(option=><option key={String(option.value)} value={String(option.value)}>{valueLabel(option.value,option.taxonomyLabel)}</option>)}</select>:field.kind==='boolean'?<select aria-label={label} value={value===undefined?'':String(value)} onChange={e=>onChange(e.target.value==='true')}><option value="">Выберите значение</option><option value="true">Да</option><option value="false">Нет</option></select>:field.kind==='number'?<input aria-label={label} type="number" min="0" step="any" value={value===undefined?'':String(value)} onChange={e=>onChange(e.target.value===''?undefined:Number(e.target.value))}/>:field.kind==='rational_inch'?<input aria-label={label} placeholder="1/2" value={typeof value==='object'&&value?`${(value as any).numerator}/${(value as any).denominator}`:String(value??'')} onChange={e=>{const match=/^(\d+)\/(\d+)$/.exec(e.target.value);onChange(match?{numerator:Number(match[1]),denominator:Number(match[2]),unit:'inch'}:e.target.value)}}/>:<p className="warning-text">Редактор этого поля пока не поддерживается: {field.technicalReason}</p>}</label><small>{field.jsonPointer}</small>{field.confirmedAt&&<small> · Подтверждено вручную</small>}{error&&<p className="error-text">{error}</p>}</div>}
type SaveResult={errors?:Record<string,string>};
function ReviewCard({row,onSave}:{row:CatalogReviewRow;onSave:(sourceItemId:string,edits:CatalogManualEdit[])=>Promise<SaveResult>}){const fields=useMemo(()=>buildCatalogEditFields(row.item),[row.item]),[values,setValues]=useState<Record<string,unknown>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);useEffect(()=>setValues(Object.fromEntries(fields.map(field=>[field.jsonPointer,field.currentValue]))),[fields]);const edits:CatalogManualEdit[]=fields.filter(field=>values[field.jsonPointer]!==undefined&&JSON.stringify(values[field.jsonPointer])!==JSON.stringify(field.currentValue)).map(field=>({jsonPointer:field.jsonPointer,value:values[field.jsonPointer]}));
  return <article className="card review-row" data-status={row.status}><h3>{row.rawName}</h3><p>{row.supplierSku&&<>Арт. {row.supplierSku} · </>}{row.status==='unsupported'?'Не поддерживается текущим справочником товаров':row.status==='invalid'?'Ошибка разметки':row.classId}</p>{row.status==='needs_review'&&<><p>Требуется заполнить: {new Set([...row.unknownFields,...row.issues.map(x=>x.json_pointer),...row.ambiguities.filter(x=>x.blocking!==false).map(x=>x.json_pointer)]).size}</p>{fields.map(field=><FieldEditor key={field.jsonPointer} field={field} value={values[field.jsonPointer]} onChange={value=>setValues(old=>({...old,[field.jsonPointer]:value}))} error={errors[field.jsonPointer]}/>)}<button className="button" disabled={saving||!edits.length} onClick={()=>onSavedLocal(edits)}>{saving?'Сохранение…':'Сохранить изменения'}</button></>}{row.status==='unsupported'&&<p>{unsupportedReasonDescription(row.unsupportedReasonCode)}</p>}{row.status==='invalid'&&row.issues.map((issue,index)=><p key={index}>{issue.message??'Разметка не соответствует контракту каталога.'}</p>)}{row.status==='validated'&&<p>Разметка подтверждена.</p>}<p><strong>Исходное наименование:</strong> “{row.source.raw_name??row.rawName}”</p><TechnicalDetails row={row}/></article>;
  async function onSavedLocal(changes:CatalogManualEdit[]){setSaving(true);setErrors({});try{const result=await onSave(row.sourceItemId,changes);setErrors(result.errors??{})}finally{setSaving(false)}}}
export function CatalogReviewPage(){const{recordId}=useParams(),[record,setRecord]=useState<CatalogRecord|null|undefined>(),[filter,setFilter]=useState<Filter>('needs_review'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[feedback,setFeedback]=useState('');const load=()=>catalogsRepository.get(recordId??'').then(value=>setRecord(value??null));useEffect(()=>{void load()},[recordId]);const rows=useMemo(()=>record?buildCatalogReviewRows(record.bundle):[],[record]),counts=record?getCatalogItemStatusCounts(record.bundle):null,filtered=useMemo(()=>{const needle=query.toLocaleLowerCase();return rows.filter(row=>(filter==='all'||row.status===filter)&&(!needle||[row.rawName,row.supplierSku,row.sourceItemId,row.classId].some(x=>x?.toLocaleLowerCase().includes(needle))))},[rows,filter,query]);useEffect(()=>setPage(0),[filter,query]);
  async function saveItem(sourceItemId:string,edits:CatalogManualEdit[]):Promise<SaveResult>{
    if(!record)return{};
    const editedSnapshot=record;
    const result=applyCatalogReviewEdits({record:editedSnapshot,sourceItemId,edits,now:new Date().toISOString()});
    if(!result.ok)return{errors:Object.fromEntries((result.errors??[]).map(error=>[error.path?.replace(/^\/items\/\d+\/catalog_item/,'')??'',error.message]))};
    try{
      await catalogsRepository.updateReviewedCatalog({recordId:editedSnapshot.recordId,expectedSemanticRevision:editedSnapshot.semanticRevision,next:result.record});
      setRecord(result.record);
      setFeedback(result.becameValidated?'Позиция проверена и теперь участвует в подборе.':`Изменения сохранены. Осталось заполнить: ${result.remainingReviewCount}.`);
    }catch(error){
      if(!(error instanceof CatalogRevisionChangedError))throw error;
      await load();
      setFeedback('Каталог был изменён в другой вкладке. Данные обновлены — проверьте позицию ещё раз.');
    }
    return{};
  }
  if(record===undefined)return <p role="status">Загрузка каталога…</p>;if(record===null)return <><PageHeader title="Каталог не найден"/><Link to="/catalogs">Вернуться к каталогам</Link></>;const filters:Array<[Filter,string,number]>=[['needs_review','Нужно заполнить',counts?.needsReview??0],['unsupported','Не поддерживаются',counts?.unsupported??0],['invalid','Ошибки',counts?.invalid??0],['validated','Готовы',counts?.validated??0],['all','Все',counts?.total??0]],slice=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);return <><Link to="/catalogs">← Каталоги</Link><PageHeader title={`Каталог: ${record.catalogId}`} description={`${record.sourceFileName} · revision ${record.semanticRevision}`}/>{feedback&&<p className="notice" role="status">{feedback}</p>}<nav className="review-filters">{filters.map(([id,label,count])=><button key={id} className={filter===id?'button':'button button--secondary'} onClick={()=>setFilter(id)}>{label} {count}</button>)}</nav><label>Поиск по товару<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{slice.map(row=><ReviewCard key={row.sourceItemId} row={row} onSave={saveItem}/>)}{!slice.length&&<p className="notice">Нет позиций для выбранного фильтра.</p>}<div className="actions"><button disabled={!page} onClick={()=>setPage(x=>x-1)}>Назад</button><button disabled={(page+1)*PAGE_SIZE>=filtered.length} onClick={()=>setPage(x=>x+1)}>Далее</button></div></>}
