import {beforeEach,describe,expect,it} from 'vitest';
import {cleanup,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import mixed from '../../../../tests/fixtures/bundles/catalog.mixed.json';
import valid from '../../../../tests/fixtures/bundles/catalog.valid.json';
import {createCatalogRecord,type CatalogBundle} from '../../domain/catalog';
import {PAGE_SIZE} from '../../domain/catalog-review';
import {resetDatabaseConnection} from '../../storage/database';
import {catalogsRepository} from '../../storage/catalogs-repository';
import {CatalogReviewPage} from './CatalogReviewPage';
import {applyCatalogReviewEdits} from '../../domain/catalog-review-edit';

beforeEach(async()=>{resetDatabaseConnection();await new Promise<void>(resolve=>{const request=indexedDB.deleteDatabase('auto-offer');request.onsuccess=()=>resolve()})});
async function show(bundle=mixed as CatalogBundle){const record={...createCatalogRecord(bundle),recordId:'review-record'};await catalogsRepository.save(record);render(<MemoryRouter initialEntries={['/catalogs/review-record/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);await screen.findByRole('heading',{name:`Каталог: ${record.catalogId}`});return record}
function reviewBundle(pointers:string[]){const bundle=structuredClone((valid as CatalogBundle));const item=bundle.items[0].catalog_item!;item.annotation!.status='needs_review';item.annotation!.unknown_fields=pointers;item.annotation!.issues=[];item.annotation!.ambiguities=[];for(const pointer of pointers){delete item.attributes![pointer.split('/').at(-1)!];item.annotation!.evidence=item.annotation!.evidence!.filter(entry=>entry.json_pointer!==pointer)}return bundle}
function productionFittingReviewBundle(){const bundle=structuredClone(valid as CatalogBundle),item=bundle.items[0].catalog_item!;item.class_id='fitting.axial';item.attributes={};item.ports=[];item.annotation={status:'needs_review',unknown_fields:['/attributes/construction','/ports/0/connection_kind'],issues:[{code:'MISSING_REQUIRED_EVIDENCE',details:{missing_paths:['/attributes/construction','/ports/0/connection_kind']}}],ambiguities:[],evidence:[{json_pointer:'/class_id',source_text:'synthetic evidence'}]};return bundle}

describe('CatalogReviewPage',()=>{it('loads the persisted mixed catalog and defaults to operator work',async()=>{await show();expect(screen.getByRole('button',{name:'Готовы 1'})).toBeVisible();expect(screen.getAllByRole('article')).toHaveLength(1);expect(screen.queryByText('Синтетический кран шаровой')).not.toBeInTheDocument()});
it('filters and searches by supported catalog identifiers',async()=>{await show();const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Нужно заполнить 1'}));expect(screen.getAllByRole('article')).toHaveLength(1);await user.type(screen.getByRole('searchbox',{name:'Поиск по товару'}),'SYN-VALVE-001');expect(screen.getByRole('heading',{name:'Synthetic needs_review'})).toBeVisible();await user.clear(screen.getByRole('searchbox'));await user.type(screen.getByRole('searchbox'),'missing');expect(screen.getByText('Нет позиций для выбранного фильтра.')).toBeVisible()});
it('expands source, reasons, evidence and current semantic values without persistence changes',async()=>{const bundle=structuredClone(mixed) as CatalogBundle,annotation=bundle.items[1].catalog_item!.annotation!;annotation.unknown_fields=['/attributes/profile'];annotation.ambiguities=[{code:'AMBIGUOUS_VALUE',json_pointer:'/attributes/profile',source_text:'неясно'}];const record=await show(bundle),before=await catalogsRepository.get(record.recordId),user=userEvent.setup();const card=screen.getByRole('heading',{name:'Synthetic needs_review'}).closest('article')!;expect(within(card).getAllByText('/attributes/profile').length).toBeGreaterThan(0);expect(card).toHaveTextContent('REVIEW_REQUIRED');expect(card).toHaveTextContent('AMBIGUOUS_VALUE');expect(card).toHaveTextContent('evidence / operator_confirmations');expect(card).toHaveTextContent('body_material');expect(card).toHaveTextContent('compression');expect(card).toHaveTextContent('raw_fields');expect(await catalogsRepository.get(record.recordId)).toEqual(before)});
it('renders only one bounded page and advances in source order',async()=>{const template=(mixed as CatalogBundle).items[1],bundle=structuredClone(mixed) as CatalogBundle;bundle.items=Array.from({length:PAGE_SIZE+2},(_,index)=>{const entry=structuredClone(template);entry.source!.raw_name=`Review row ${index+1}`;entry.catalog_item!.source_item_id=`row-${index+1}`;return entry});await show(bundle);expect(screen.getAllByRole('article')).toHaveLength(PAGE_SIZE);expect(screen.queryByRole('heading',{name:'Review row 51'})).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Далее'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Review row 51'})).toBeVisible());expect(screen.getAllByRole('article')).toHaveLength(2)});
it('persists a partial save and restores it after reopening',async()=>{const bundle=reviewBundle(['/attributes/body_material','/attributes/handle_type']),source=structuredClone(bundle.items[0].source),record=await show(bundle),user=userEvent.setup();await user.selectOptions(screen.getByRole('combobox',{name:'Материал'}),'brass');await user.click(screen.getByRole('button',{name:'Сохранить изменения'}));await screen.findByText('Изменения сохранены. Осталось заполнить: 1.');const stored=await catalogsRepository.get(record.recordId),item=stored!.bundle.items[0].catalog_item!;expect(item.attributes?.body_material).toBe('brass');expect(item.annotation).toMatchObject({status:'needs_review',unknown_fields:['/attributes/handle_type'],operator_confirmations:[{json_pointer:'/attributes/body_material',value:'brass'}]});expect(stored).toMatchObject({semanticRevision:1,sourceSha256:record.sourceSha256});expect(stored!.bundle.items[0].source).toEqual(source);cleanup();render(<MemoryRouter initialEntries={['/catalogs/review-record/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);await screen.findByRole('combobox',{name:'Материал'});await waitFor(()=>expect(screen.getByRole('combobox',{name:'Материал'})).toHaveValue('brass'));expect(screen.getByRole('button',{name:'Нужно заполнить 1'})).toBeVisible();expect(screen.getByText('Требуется заполнить: 1')).toBeVisible()});
it('persists the final edit and moves the item to ready',async()=>{const record=await show(reviewBundle(['/attributes/handle_type'])),user=userEvent.setup();await user.selectOptions(screen.getByRole('combobox',{name:'Тип рукоятки'}),'lever');await user.click(screen.getByRole('button',{name:'Сохранить изменения'}));expect(await screen.findByText('Позиция проверена и теперь участвует в подборе.')).toBeVisible();expect(await catalogsRepository.get(record.recordId)).toMatchObject({semanticRevision:1,validatedCount:1,needsReviewCount:0,bundle:{items:[{catalog_item:{annotation:{status:'validated'}}}]}});expect(screen.getByRole('button',{name:'Нужно заполнить 0'})).toBeVisible();expect(screen.getByText('Нет позиций для выбранного фильтра.')).toBeVisible();await user.click(screen.getByRole('button',{name:'Готовы 1'}));expect(screen.getByRole('heading',{name:'Синтетический кран шаровой'})).toBeVisible()});
it('completes the production-shaped fitting flow and materializes its missing port',async()=>{const record=await show(productionFittingReviewBundle()),user=userEvent.setup(),card=screen.getByRole('article');expect(card).toHaveTextContent('Аксиальный фитинг');expect(card).not.toHaveTextContent('Арт. SYN-VALVE-001 · fitting.axial');expect(screen.getByText('Требуется заполнить: 2')).toBeVisible();expect(within(screen.getByRole('combobox',{name:'Тип фитинга'})).getByRole('option',{name:'Переходник'})).toHaveValue('adapter');await user.selectOptions(screen.getByRole('combobox',{name:'Тип фитинга'}),'adapter');await user.click(screen.getByRole('button',{name:'Сохранить изменения'}));expect(await screen.findByText('Изменения сохранены. Осталось заполнить: 1.')).toBeVisible();let stored=await catalogsRepository.get(record.recordId);expect(stored!.bundle.items[0].catalog_item!.annotation).toMatchObject({status:'needs_review',issues:[{details:{missing_paths:['/ports/0/connection_kind']}}]});await user.selectOptions(screen.getByRole('combobox',{name:'Тип соединения — сторона 1'}),'female_thread');await user.click(screen.getByRole('button',{name:'Сохранить изменения'}));expect(await screen.findByText('Позиция проверена и теперь участвует в подборе.')).toBeVisible();stored=await catalogsRepository.get(record.recordId);expect(stored!.bundle.items[0].catalog_item).toMatchObject({attributes:{construction:'adapter'},ports:[{role:'end_1',connection_kind:'female_thread'}],annotation:{status:'validated',issues:[],operator_confirmations:[{json_pointer:'/attributes/construction',value:'adapter'},{json_pointer:'/ports/0/connection_kind',value:'female_thread'}]}});cleanup();render(<MemoryRouter initialEntries={['/catalogs/review-record/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);await screen.findByRole('heading',{name:`Каталог: ${record.catalogId}`});await user.click(screen.getByRole('button',{name:'Готовы 1'}));expect(screen.getByRole('article')).toHaveTextContent('Аксиальный фитинг')});
it('rejects a stale form, reloads the winner, and shows conflict feedback',async()=>{const record=await show(reviewBundle(['/attributes/body_material','/attributes/handle_type'])),snapshot=await catalogsRepository.get(record.recordId),user=userEvent.setup();await user.selectOptions(screen.getByRole('combobox',{name:'Тип рукоятки'}),'lever');const external=applyCatalogReviewEdits({record:snapshot!,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/body_material',value:'brass'}],now:'2026-08-10T12:00:00.000Z'});expect(external.ok).toBe(true);if(!external.ok)return;await catalogsRepository.updateReviewedCatalog({recordId:record.recordId,expectedSemanticRevision:0,next:external.record});await user.click(screen.getByRole('button',{name:'Сохранить изменения'}));expect(await screen.findByText('Каталог был изменён в другой вкладке. Данные обновлены — проверьте позицию ещё раз.')).toBeVisible();const stored=await catalogsRepository.get(record.recordId);expect(stored).toMatchObject({semanticRevision:1,bundle:{items:[{catalog_item:{attributes:{body_material:'brass'},annotation:{status:'needs_review',unknown_fields:['/attributes/handle_type']}}}]}});expect(stored!.bundle.items[0].catalog_item!.attributes?.handle_type).toBeUndefined();expect(screen.getByRole('combobox',{name:'Материал'})).toHaveValue('brass');expect(screen.getByRole('combobox',{name:'Тип рукоятки'})).toHaveValue('')});
it('shows a safe missing-catalog state',async()=>{render(<MemoryRouter initialEntries={['/catalogs/missing/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Каталог не найден'})).toBeVisible();expect(screen.getByRole('link',{name:'Вернуться к каталогам'})).toHaveAttribute('href','/catalogs')})});
