import {beforeEach,describe,expect,it} from 'vitest';
import {render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import mixed from '../../../../tests/fixtures/bundles/catalog.mixed.json';
import {createCatalogRecord,type CatalogBundle} from '../../domain/catalog';
import {PAGE_SIZE} from '../../domain/catalog-review';
import {resetDatabaseConnection} from '../../storage/database';
import {catalogsRepository} from '../../storage/catalogs-repository';
import {CatalogReviewPage} from './CatalogReviewPage';

beforeEach(async()=>{resetDatabaseConnection();await new Promise<void>(resolve=>{const request=indexedDB.deleteDatabase('auto-offer');request.onsuccess=()=>resolve()})});
async function show(bundle=mixed as CatalogBundle){const record={...createCatalogRecord(bundle),recordId:'review-record'};await catalogsRepository.save(record);render(<MemoryRouter initialEntries={['/catalogs/review-record/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);await screen.findByRole('heading',{name:`Каталог: ${record.catalogId}`});return record}

describe('CatalogReviewPage',()=>{it('loads the persisted mixed catalog and defaults to its three problem rows',async()=>{await show();expect(screen.getByRole('button',{name:'Validated 1'})).toBeVisible();expect(screen.getAllByRole('article')).toHaveLength(3);expect(screen.queryByText('Синтетический кран шаровой')).not.toBeInTheDocument()});
it('filters and searches by supported catalog identifiers',async()=>{await show();const user=userEvent.setup();await user.click(screen.getByRole('button',{name:'Требуют проверки 1'}));expect(screen.getAllByRole('article')).toHaveLength(1);await user.type(screen.getByRole('searchbox',{name:'Поиск по товару'}),'SYN-VALVE-001');expect(screen.getByRole('heading',{name:'Synthetic needs_review'})).toBeVisible();await user.clear(screen.getByRole('searchbox'));await user.type(screen.getByRole('searchbox'),'missing');expect(screen.getByText('По вашему запросу ничего не найдено.')).toBeVisible()});
it('expands source, reasons, evidence and current semantic values without persistence changes',async()=>{const bundle=structuredClone(mixed) as CatalogBundle,annotation=bundle.items[1].catalog_item!.annotation!;annotation.unknown_fields=['/attributes/profile'];annotation.ambiguities=[{code:'AMBIGUOUS_VALUE',json_pointer:'/attributes/profile',source_text:'неясно'}];const record=await show(bundle),before=await catalogsRepository.get(record.recordId),user=userEvent.setup();await user.click(screen.getByRole('button',{name:/Подробнее: Synthetic needs_review/}));const card=screen.getByRole('heading',{name:'Synthetic needs_review'}).closest('article')!;expect(within(card).getAllByText('/attributes/profile').length).toBeGreaterThan(0);expect(card).toHaveTextContent('REVIEW_REQUIRED');expect(card).toHaveTextContent('AMBIGUOUS_VALUE');expect(card).toHaveTextContent('Подтверждено источником');expect(card).toHaveTextContent('body_material');expect(card).toHaveTextContent('compression');expect(card).toHaveTextContent('raw_fields');expect(await catalogsRepository.get(record.recordId)).toEqual(before)});
it('renders only one bounded page and advances in source order',async()=>{const template=(mixed as CatalogBundle).items[1],bundle=structuredClone(mixed) as CatalogBundle;bundle.items=Array.from({length:PAGE_SIZE+2},(_,index)=>{const entry=structuredClone(template);entry.source!.raw_name=`Review row ${index+1}`;entry.catalog_item!.source_item_id=`row-${index+1}`;return entry});await show(bundle);expect(screen.getAllByRole('article')).toHaveLength(PAGE_SIZE);expect(screen.queryByRole('heading',{name:'Review row 51'})).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Далее'}));await waitFor(()=>expect(screen.getByRole('heading',{name:'Review row 51'})).toBeVisible());expect(screen.getAllByRole('article')).toHaveLength(2)});
it('shows a safe missing-catalog state',async()=>{render(<MemoryRouter initialEntries={['/catalogs/missing/review']}><Routes><Route path="catalogs/:recordId/review" element={<CatalogReviewPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Каталог не найден'})).toBeVisible();expect(screen.getByRole('link',{name:'Вернуться к каталогам'})).toHaveAttribute('href','/catalogs')})});
