import {
  classifyCatalogValidationInputs,
  preflightCatalogValidationInputs,
} from './input-contract.mjs';

const GENERATOR_VERSION = '1.0.0';
const FORMAT_VERSION = '1.0.0';
const MODULE_EXPORT_ROLES = Object.freeze({
  validateCatalogBundle: 'bundle_validator',
  validateAnnotation: 'annotation_contract_validator',
  classifyGtin: 'catalog_identifiers',
  buildRequestPortContracts: 'request_port_contracts',
});

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map(key => [key, stable(value[key])]));
  }
  return value;
}

const canonicalJson = value => JSON.stringify(stable(value));
const utf8Bytes = value => new TextEncoder().encode(value);

async function sha256(value) {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) throw new Error('Web Crypto SHA-256 is unavailable');
  const digest = new Uint8Array(await subtle.digest('SHA-256', utf8Bytes(value)));
  return [...digest].map(byte => byte.toString(16).padStart(2, '0')).join('');
}

function base64Utf8(value) {
  const bytes = utf8Bytes(value);
  let binary = '';
  const chunkSize = 0x8000;
  for (let index = 0; index < bytes.length; index += chunkSize) {
    binary += String.fromCharCode(...bytes.subarray(index, Math.min(index + chunkSize, bytes.length)));
  }
  return btoa(binary);
}

const moduleDataUrl = source => `data:text/javascript;base64,${base64Utf8(source)}`;

function importedTargetRole(importedNames) {
  const roles = [...new Set(importedNames.map(name => MODULE_EXPORT_ROLES[name]).filter(Boolean))];
  return roles.length === 1 ? roles[0] : null;
}

function replaceSpecifier(source, specifier, replacement) {
  const single = `'${specifier}'`;
  const double = `"${specifier}"`;
  const next = source.replaceAll(single, `'${replacement}'`).replaceAll(double, `"${replacement}"`);
  if (next === source) throw new Error(`Import specifier ${specifier} was not found during module linking`);
  return next;
}

function linkSemanticModules(modules) {
  const cache = new Map();
  const active = new Set();

  function link(role) {
    if (cache.has(role)) return cache.get(role);
    if (active.has(role)) throw new Error(`Semantic module import cycle at ${role}`);
    const record = modules[role];
    if (!record) throw new Error(`Semantic module role ${role} is missing`);
    active.add(role);
    let source = record.text;
    for (const imported of record.imports) {
      const targetRole = importedTargetRole(imported.importedNames);
      if (!targetRole) throw new Error(`Cannot resolve ${imported.specifier} from ${role}`);
      source = replaceSpecifier(source, imported.specifier, link(targetRole));
    }
    active.delete(role);
    const url = moduleDataUrl(`${source.trim()}\n`);
    cache.set(role, url);
    return url;
  }

  return {
    bundleValidatorUrl: link('bundle_validator'),
    urls: Object.fromEntries(Object.keys(modules).sort().map(role => [role, link(role)])),
  };
}

async function sourceMetadata(classified) {
  const records = Object.values(classified.roles).sort((left, right) => left.name.localeCompare(right.name));
  const entries = await Promise.all(records.map(async record => [record.name, {
    bytes: utf8Bytes(record.text).length,
    sha256: await sha256(record.text),
  }]));
  return Object.fromEntries(entries);
}

function generatedModuleSource({ metadata, kit, registry, ajvRuntimeSource, bundleValidatorUrl }) {
  const metadataJson = canonicalJson(metadata);
  const kitJson = canonicalJson(kit);
  const registryJson = canonicalJson(registry);
  const ajvRuntimeUrl = moduleDataUrl(`${ajvRuntimeSource.trim()}\n`);
  const lines = [
    '// Generated by Auto Offer catalog validation kit builder. Do not edit.',
    `export const kitMetadata = Object.freeze(${metadataJson});`,
    `export const annotationKit = Object.freeze(${kitJson});`,
    `export const classSchemaRegistry = Object.freeze(${registryJson});`,
    `const AJV_RUNTIME_URL = ${JSON.stringify(ajvRuntimeUrl)};`,
    `const BUNDLE_VALIDATOR_URL = ${JSON.stringify(bundleValidatorUrl)};`,
    '',
    'const kit = annotationKit;',
    'const registry = classSchemaRegistry;',
    'let catalogValidatorPromise;',
    '',
    'export async function createCatalogValidator() {',
    '  if (!catalogValidatorPromise) catalogValidatorPromise = (async () => {',
    '    const [{ createCatalogAjv }, semantic] = await Promise.all([',
    '      import(AJV_RUNTIME_URL),',
    '      import(BUNDLE_VALIDATOR_URL),',
    '    ]);',
    '    const ajv = createCatalogAjv();',
    '    for (const schemaId of Object.keys(kit.schemas_by_id).sort()) {',
    '      ajv.addSchema(kit.schemas_by_id[schemaId], schemaId);',
    '    }',
    '    const catalogBundleValidator = ajv.getSchema(kit.root_schema_id);',
    "    const catalogItemBaseSchemaId = Object.keys(kit.schemas_by_id).find(id => id.endsWith('/catalog-item-annotation.base.schema.json'));",
    '    const catalogItemBaseValidator = catalogItemBaseSchemaId ? ajv.getSchema(catalogItemBaseSchemaId) : null;',
    "    if (!catalogBundleValidator) throw new Error('Catalog bundle root schema did not compile');",
    "    if (!catalogItemBaseValidator) throw new Error('Catalog item base schema did not compile');",
    '    const classSchemas = {};',
    '    for (const classId of Object.keys(registry.classes).sort()) {',
    '      const relativePath = registry.classes[classId].catalog_schema;',
    '      const schemaId = kit.class_schema_ids[classId];',
    '      const validator = ajv.getSchema(schemaId);',
    "      if (!validator) throw new Error(`Catalog class schema did not compile: ${classId}`);",
    '      classSchemas[relativePath] = {',
    '        class_id: classId,',
    '        schema: kit.schemas_by_id[schemaId],',
    '        validator,',
    '      };',
    '    }',
    '    const context = {',
    '      taxonomy: kit.taxonomy,',
    '      registry,',
    '      classSchemas,',
    '      catalogBundleValidator,',
    '      catalogItemBaseValidator,',
    '    };',
    '    const validate = bundle => semantic.validateCatalogBundle(bundle, context);',
    '    Object.defineProperty(validate, "context", { value: context });',
    '    return validate;',
    '  })();',
    '  return catalogValidatorPromise;',
    '}',
    '',
    'export async function validateCatalogBundle(bundle) {',
    '  const validate = await createCatalogValidator();',
    '  return validate(bundle);',
    '}',
    '',
    'export async function validateCatalogFile(filePath) {',
    "  const { readFile } = await import('node:fs/promises');",
    "  const text = await readFile(filePath, 'utf8');",
    '  return validateCatalogBundle(JSON.parse(text));',
    '}',
    '',
    'async function isMainModule() {',
    "  if (typeof process === 'undefined' || !process.versions?.node || !process.argv?.[1]) return false;",
    "  const { pathToFileURL } = await import('node:url');",
    '  return import.meta.url === pathToFileURL(process.argv[1]).href;',
    '}',
    '',
    'async function runCli(paths) {',
    '  if (!paths.length) {',
    "    console.error(JSON.stringify({ valid: false, code: 'USAGE_ERROR', message: 'Usage: node catalog-validation-kit.mjs <catalog.json> [...]' }));",
    '    return 2;',
    '  }',
    '  let exitCode = 0;',
    "  const { readFile } = await import('node:fs/promises');",
    '  for (const file of paths) {',
    '    let text;',
    '    try {',
    "      text = await readFile(file, 'utf8');",
    '    } catch (cause) {',
    "      console.error(JSON.stringify({ file, valid: false, code: 'FILE_READ_ERROR', message: cause instanceof Error ? cause.message : String(cause) }));",
    '      exitCode = 2;',
    '      continue;',
    '    }',
    '    let bundle;',
    '    try {',
    '      bundle = JSON.parse(text);',
    '    } catch (cause) {',
    "      console.error(JSON.stringify({ file, valid: false, code: 'JSON_PARSE_ERROR', message: cause instanceof Error ? cause.message : String(cause) }));",
    '      exitCode = 2;',
    '      continue;',
    '    }',
    '    const result = await validateCatalogBundle(bundle);',
    '    console.log(JSON.stringify({ file, ...result }));',
    '    if (!result.valid && exitCode === 0) exitCode = 1;',
    '  }',
    '  return exitCode;',
    '}',
    '',
    'if (await isMainModule()) process.exitCode = await runCli(process.argv.slice(2));',
    '',
  ];
  return lines.join('\n');
}

export class CatalogValidationKitInputError extends Error {
  constructor(diagnostics) {
    super('Catalog validation kit inputs failed preflight');
    this.name = 'CatalogValidationKitInputError';
    this.diagnostics = diagnostics;
  }
}

export async function buildCatalogValidationKit(files, { ajvRuntimeSource } = {}) {
  if (typeof ajvRuntimeSource !== 'string' || !ajvRuntimeSource.trim()) {
    throw new TypeError('ajvRuntimeSource must be a non-empty bundled ESM source');
  }
  const classified = classifyCatalogValidationInputs(files);
  const preflight = preflightCatalogValidationInputs(classified);
  if (!preflight.ok) throw new CatalogValidationKitInputError(preflight);
  const linked = linkSemanticModules(preflight.modules);
  const metadata = stable({
    format_version: FORMAT_VERSION,
    generator_version: GENERATOR_VERSION,
    taxonomy_version: preflight.summary.taxonomy_version,
    annotation_schema_version: preflight.summary.annotation_schema_version,
    bundle_schema_version: preflight.summary.bundle_schema_version,
    class_count: preflight.summary.class_count,
    schema_count: preflight.summary.schema_count,
    module_count: preflight.summary.module_count,
    sources: await sourceMetadata(classified),
  });
  const source = generatedModuleSource({
    metadata,
    kit: preflight.kit,
    registry: preflight.registry,
    ajvRuntimeSource,
    bundleValidatorUrl: linked.bundleValidatorUrl,
  });
  return {
    source,
    bytes: utf8Bytes(source).length,
    sha256: await sha256(source),
    metadata,
    diagnostics: {
      warnings: preflight.warnings,
      semantic_module_urls: Object.keys(linked.urls).sort(),
    },
  };
}
