import { useRef, useState } from "react";
import semanticPrompt from "../../../../../annotation-kits/matching/SEMANTIC_MATCH_PROMPT.md?raw";
import type { SessionMatchingSettings } from "../../../domain/matching/session-policy";
import { importSemanticMatchResult, prepareSemanticMatchingPackage, SemanticImportError } from "../../../domain/matching/semantic-session-matching";
import { appRepositories } from "../../../storage/repositories";
import { downloadTextFile } from "../../../lib/download-file";

export function SemanticMatchingWorkspace({sessionId,settings,disabled}:{sessionId:string;settings:SessionMatchingSettings;disabled:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState<string>(),file=useRef<HTMLInputElement>(null);
 const prepare=async()=>{setBusy(true);setMessage(undefined);try{const prepared=await prepareSemanticMatchingPackage({sessionId,settings,repositories:appRepositories});downloadTextFile("SEMANTIC_MATCH_PROMPT.md",semanticPrompt,"text/markdown");downloadTextFile("request_bundle.json",JSON.stringify(prepared.session.requestBundle,null,2));downloadTextFile("semantic-matching-catalog.json",JSON.stringify(prepared.matchingCatalog,null,2));setMessage("Файлы готовы. Откройте новый чат с ИИ, загрузите три скачанных файла и получите semantic-match-result.json.");}catch(e){setMessage(e instanceof Error?e.message:"Не удалось подготовить пакет");}finally{setBusy(false)}};
 const importFile=async(e:React.ChangeEvent<HTMLInputElement>)=>{const selected=e.target.files?.[0];if(!selected)return;setBusy(true);setMessage(undefined);try{const parsed:unknown=JSON.parse(await selected.text());await importSemanticMatchResult({sessionId,semanticResult:parsed,repositories:appRepositories});setMessage("Подбор ИИ загружен. Открываем его для проверки…");window.location.reload();}catch(error){setMessage(error instanceof SyntaxError?"JSON результата имеет неверный формат":error instanceof SemanticImportError?error.message:error instanceof Error?error.message:"Файл не импортирован");}finally{e.target.value="";setBusy(false)}};
 return <section className="card" aria-label="Шаг 3 — Подбор наших товаров"><h2>Шаг 3 — Подбор наших товаров</h2><p>Приложение подготовит заявку и подходящие товары из ваших каталогов. ИИ выберет товар для каждой позиции, а Auto Offer проверит результат. Используется внешний чат с ИИ.</p><ol><li>Подготовить файлы.</li><li>Открыть новый чат с ИИ и приложить три файла.</li><li>Загрузить полученный результат.</li></ol><div className="row"><button type="button" disabled={disabled||busy} onClick={prepare}>Подготовить подбор для ИИ</button><button type="button" disabled={disabled||busy} onClick={()=>file.current?.click()}>Загрузить результат ИИ</button><input ref={file} hidden aria-label="semantic-match-result.json" type="file" accept="application/json,.json" onChange={importFile}/></div>{message&&<p role="status">{message}</p>}</section>;
}
