import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {
  externalRefs,
  generateKits,
  repositoryRoot,
  roots,
} from '../scripts/annotation-kits/lib/annotation-kits.mjs';

const kitPath = (kind) => path.join(repositoryRoot, `annotation-kits/${kind}-annotation-kit.json`);
const readJson = async (file) => JSON.parse(await readFile(file, 'utf8'));
const digest = async (file) => createHash('sha256').update(await readFile(file)).digest('hex');

function containsClassConst(value, classId) {
  if (!value || typeof value !== 'object') return false;
  if (value.const === classId) return true;
  return Object.values(value).some((child) => containsClassConst(child, classId));
}

test('kits have the required structure, taxonomy, mappings, and closed references', async () => {
  const taxonomy = await readJson(path.join(repositoryRoot, 'taxonomy/taxonomy.json'));
  const expectedClasses = Object.keys(taxonomy.classes).sort();

  for (const kind of ['catalog', 'request']) {
    const kit = await readJson(kitPath(kind));
    assert.equal(kit.kit_schema_version, '1.0.0');
    assert.equal(kit.kit_version, '1.2.0');
    assert.equal(kit.kind, `${kind}_annotation_kit`);
    assert.equal(kit.root_schema_id, roots[kind]);
    assert.equal(kit.class_count, 41);
    assert.equal(kit.taxonomy_version, taxonomy.taxonomy_version);
    assert.deepEqual(kit.taxonomy, taxonomy);
    assert.deepEqual(Object.keys(kit.class_schema_ids).sort(), expectedClasses);

    for (const [classId, schemaId] of Object.entries(kit.class_schema_ids)) {
      assert.ok(kit.schemas_by_id[schemaId], `${schemaId} must be embedded`);
      assert.ok(containsClassConst(kit.schemas_by_id[schemaId], classId), `${schemaId} must constrain ${classId}`);
    }
    for (const [schemaId, schema] of Object.entries(kit.schemas_by_id)) {
      for (const ref of externalRefs(schema)) {
        assert.ok(kit.schemas_by_id[ref], `${ref}, referenced by ${schemaId}, must resolve`);
      }
    }

    const forbidden = kind === 'catalog' ? '.request.schema.json' : '.catalog.schema.json';
    assert.equal(Object.keys(kit.schemas_by_id).filter((id) => id.includes('/class-specific/') && id.endsWith(forbidden)).length, 0);
    assert.equal(Object.keys(kit.schemas_by_id).filter((id) => id.includes('/class-specific/')).length, 41);
  }
});

test('generation is byte-identical and does not modify source contracts', async () => {
  const sourceFiles = [
    'taxonomy/taxonomy.json',
    'schemas/annotation/class-schema-registry.json',
    'schemas/annotation/common.schema.json',
    'schemas/bundles/catalog-bundle.schema.json',
    'schemas/bundles/request-bundle.schema.json',
  ].map((file) => path.join(repositoryRoot, file));
  const sourcesBefore = await Promise.all(sourceFiles.map(digest));
  const before = await Promise.all(['catalog', 'request'].map((kind) => readFile(kitPath(kind))));
  await generateKits();
  const afterFirst = await Promise.all(['catalog', 'request'].map((kind) => readFile(kitPath(kind))));
  await generateKits();
  const afterSecond = await Promise.all(['catalog', 'request'].map((kind) => readFile(kitPath(kind))));
  assert.deepEqual(afterFirst, before);
  assert.deepEqual(afterSecond, afterFirst);
  assert.deepEqual(await Promise.all(sourceFiles.map(digest)), sourcesBefore);
});

test('manifest describes the exact generated bytes', async () => {
  const manifest = await readJson(path.join(repositoryRoot, 'annotation-kits/annotation-kits-manifest.json'));
  assert.equal(manifest.manifest_schema_version, '1.0.0');
  for (const kind of ['catalog', 'request']) {
    const bytes = await readFile(kitPath(kind));
    const kit = JSON.parse(bytes);
    const entry = manifest.kits[kind];
    assert.equal(entry.path, `annotation-kits/${kind}-annotation-kit.json`);
    assert.equal(entry.sha256, createHash('sha256').update(bytes).digest('hex'));
    assert.equal(entry.bytes, bytes.length);
    assert.equal(entry.class_count, Object.keys(kit.class_schema_ids).length);
    assert.equal(entry.schema_count, Object.keys(kit.schemas_by_id).length);
  }
});
