import {describe,expect,it} from 'vitest';
import bundleFixture from '../../../tests/fixtures/bundles/catalog.valid.json';
import {createCatalogRecord,type CatalogBundle} from './catalog';
import {applyCatalogReviewEdits} from './catalog-review-edit';
import {buildCatalogEditFields} from './catalog-review-fields';
import {fieldLabel,valueLabel} from '../features/catalogs/catalog-review-presentation';
function reviewRecord(pointers:string[]){const bundle=structuredClone(bundleFixture) as CatalogBundle,item=bundle.items[0].catalog_item!;item.annotation!.status='needs_review';item.annotation!.unknown_fields=pointers;item.annotation!.issues=[];item.annotation!.ambiguities=[];for(const pointer of pointers){const key=pointer.split('/').at(-1)!;delete item.attributes![key];item.annotation!.evidence=item.annotation!.evidence!.filter(x=>x.json_pointer!==pointer)}return createCatalogRecord(bundle,12,'2026-08-10T10:00:00.000Z')}
describe('catalog review edit domain',()=>{
 it('persists a partial semantic edit without changing source provenance',()=>{const record=reviewRecord(['/attributes/body_material','/attributes/handle_type']),source=structuredClone(record.bundle.items[0].source),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/body_material',value:'brass'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(!result.ok)return;const item=result.record.bundle.items[0].catalog_item!;expect(item.annotation).toMatchObject({status:'needs_review',unknown_fields:['/attributes/handle_type'],operator_confirmations:[{json_pointer:'/attributes/body_material',value:'brass'}]});expect(result.record.bundle.items[0].source).toEqual(source);expect(result.record.sourceSha256).toBe(record.sourceSha256);expect(result.record.semanticRevision).toBe(1)});
 it('validates the final edit and recomputes counts',()=>{const record=reviewRecord(['/attributes/handle_type']),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/handle_type',value:'lever'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(result.ok){expect(result.becameValidated).toBe(true);expect(result.record.validatedCount).toBe(1);expect(result.record.needsReviewCount).toBe(0)}});
 it('rejects a non-canonical enum without mutating the record',()=>{const record=reviewRecord(['/attributes/handle_type']),before=structuredClone(record),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/handle_type',value:'invented'}],now:'2026-08-10T11:30:00.000Z'});expect(result).toMatchObject({ok:false,code:'INVALID_EDIT'});expect(record).toEqual(before)});
});
describe('human field projection',()=>{it('uses production options and readable Russian labels',()=>{const item=reviewRecord(['/attributes/handle_type']).bundle.items[0].catalog_item!,field=buildCatalogEditFields(item)[0];expect(field.options?.map(x=>x.value)).toContain('lever');expect(fieldLabel(field)).toBe('Тип рукоятки');for(const[value,label]of [['lever','Рычаг'],['manual_valves','Ручные клапаны'],['press_tool','Пресс-инструмент'],['brass','Латунь'],['female_thread','Внутренняя резьба']])expect(valueLabel(value)).toBe(label)})});
