import {describe,expect,it} from 'vitest';
import bundleFixture from '../../../tests/fixtures/bundles/catalog.valid.json';
import {createCatalogRecord,type CatalogBundle} from './catalog';
import {applyCatalogReviewEdits} from './catalog-review-edit';
import {buildCatalogEditFields} from './catalog-review-fields';
import {fieldLabel,valueLabel} from '../features/catalogs/catalog-review-presentation';
import {collectUnresolvedReviewPointers,countUnresolvedReviewReasons} from './catalog-review-reasons';
function reviewRecord(pointers:string[]){const bundle=structuredClone(bundleFixture) as CatalogBundle,item=bundle.items[0].catalog_item!;item.annotation!.status='needs_review';item.annotation!.unknown_fields=pointers;item.annotation!.issues=[];item.annotation!.ambiguities=[];for(const pointer of pointers){const key=pointer.split('/').at(-1)!;delete item.attributes![key];item.annotation!.evidence=item.annotation!.evidence!.filter(x=>x.json_pointer!==pointer)}return createCatalogRecord(bundle,12,'2026-08-10T10:00:00.000Z')}
describe('catalog review edit domain',()=>{
 it('persists a partial semantic edit without changing source provenance',()=>{const record=reviewRecord(['/attributes/body_material','/attributes/handle_type']),source=structuredClone(record.bundle.items[0].source),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/body_material',value:'brass'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(!result.ok)return;const item=result.record.bundle.items[0].catalog_item!;expect(item.annotation).toMatchObject({status:'needs_review',unknown_fields:['/attributes/handle_type'],operator_confirmations:[{json_pointer:'/attributes/body_material',value:'brass'}]});expect(result.record.bundle.items[0].source).toEqual(source);expect(result.record.sourceSha256).toBe(record.sourceSha256);expect(result.record.semanticRevision).toBe(1)});
 it('validates the final edit and recomputes counts',()=>{const record=reviewRecord(['/attributes/handle_type']),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/handle_type',value:'lever'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(result.ok){expect(result.becameValidated).toBe(true);expect(result.record.validatedCount).toBe(1);expect(result.record.needsReviewCount).toBe(0)}});
 it('rejects a non-canonical enum without mutating the record',()=>{const record=reviewRecord(['/attributes/handle_type']),before=structuredClone(record),result=applyCatalogReviewEdits({record,sourceItemId:'synthetic-valve.ball-1',edits:[{jsonPointer:'/attributes/handle_type',value:'invented'}],now:'2026-08-10T11:30:00.000Z'});expect(result).toMatchObject({ok:false,code:'INVALID_EDIT'});expect(record).toEqual(before)});
 it('resolves a production-shaped single missing path',()=>{const record=reviewRecord(['/attributes/handle_type']),item=record.bundle.items[0].catalog_item!;item.annotation!.issues=[{code:'MISSING_REQUIRED_EVIDENCE',details:{missing_paths:['/attributes/handle_type']}}];const result=applyCatalogReviewEdits({record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/attributes/handle_type',value:'lever'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(!result.ok)return;expect(result.record.bundle.items[0].catalog_item).toMatchObject({attributes:{handle_type:'lever'},annotation:{status:'validated',unknown_fields:[],issues:[],operator_confirmations:[{json_pointer:'/attributes/handle_type',value:'lever'}]}})});
 it('removes only the edited pointer from a multi-path issue',()=>{const record=reviewRecord(['/attributes/body_material','/attributes/handle_type']),item=record.bundle.items[0].catalog_item!;item.annotation!.issues=[{code:'MISSING_REQUIRED_EVIDENCE',details:{missing_paths:['/attributes/body_material','/attributes/handle_type']}}];const first=applyCatalogReviewEdits({record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/attributes/body_material',value:'brass'}],now:'2026-08-10T11:30:00.000Z'});expect(first.ok).toBe(true);if(!first.ok)return;expect(first.record.bundle.items[0].catalog_item!.annotation).toMatchObject({status:'needs_review',issues:[{details:{missing_paths:['/attributes/handle_type']}}]});const second=applyCatalogReviewEdits({record:first.record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/attributes/handle_type',value:'lever'}],now:'2026-08-10T11:31:00.000Z'});expect(second.ok).toBe(true);if(second.ok)expect(second.record.bundle.items[0].catalog_item!.annotation).toMatchObject({status:'validated',issues:[]})});
 it('materializes only the requested taxonomy port without guessing allowed values',()=>{const record=reviewRecord([]),item=record.bundle.items[0].catalog_item!;item.class_id='fitting.axial';item.attributes={};item.ports=[];item.annotation!.evidence=[{json_pointer:'/class_id',source_text:'synthetic evidence'}];item.annotation!.status='needs_review';item.annotation!.unknown_fields=['/attributes/construction','/ports/0/connection_kind'];item.annotation!.issues=[{code:'MISSING_REQUIRED_EVIDENCE',details:{missing_paths:['/attributes/construction','/ports/0/connection_kind']}}];const source=structuredClone(record.bundle.items[0].source),result=applyCatalogReviewEdits({record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/ports/0/connection_kind',value:'female_thread'}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(!result.ok)return;const edited=result.record.bundle.items[0].catalog_item!;expect(edited.ports).toEqual([{role:'end_1',connection_kind:'female_thread'}]);expect(edited.ports![0]).not.toHaveProperty('system');expect(edited.annotation).toMatchObject({status:'needs_review',unknown_fields:['/attributes/construction'],issues:[{details:{missing_paths:['/attributes/construction']}}],operator_confirmations:[{json_pointer:'/ports/0/connection_kind',value:'female_thread'}]});expect(result.record.bundle.items[0].source).toEqual(source);expect(result.record.sourceSha256).toBe(record.sourceSha256)});
 it('rejects sparse port materialization without changing the input record',()=>{const record=reviewRecord([]),item=record.bundle.items[0].catalog_item!;item.class_id='fitting.axial';item.ports=[];item.annotation!.unknown_fields=['/ports/1/connection_kind'];const before=structuredClone(record),result=applyCatalogReviewEdits({record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/ports/1/connection_kind',value:'female_thread'}],now:'2026-08-10T11:30:00.000Z'});expect(result).toMatchObject({ok:false,code:'EDIT_PATH_NOT_ALLOWED'});expect(record).toEqual(before)});
 it('materializes fixed slot data but confirms only the explicit edit',()=>{const record=reviewRecord([]),item=record.bundle.items[0].catalog_item!;item.class_id='drain.floor';item.attributes={outlet_orientation:'horizontal',seal_type:'wet'};item.ports=[];item.annotation!.evidence=[{json_pointer:'/class_id',source_text:'synthetic evidence'},{json_pointer:'/attributes/outlet_orientation',source_text:'synthetic evidence'},{json_pointer:'/attributes/seal_type',source_text:'synthetic evidence'}];item.annotation!.unknown_fields=['/ports/0/pipe_outer_diameter_mm','/ports/0/system'];item.annotation!.issues=[{code:'CONTRADICTORY_SOURCE'}];const result=applyCatalogReviewEdits({record,sourceItemId:item.source_item_id!,edits:[{jsonPointer:'/ports/0/pipe_outer_diameter_mm',value:110}],now:'2026-08-10T11:30:00.000Z'});expect(result.ok).toBe(true);if(!result.ok)return;const edited=result.record.bundle.items[0].catalog_item!;expect(edited.ports).toEqual([{role:'sewer_outlet',connection_kind:'sewer_spigot',pipe_outer_diameter_mm:110}]);expect(edited.annotation!.operator_confirmations).toEqual([{json_pointer:'/ports/0/pipe_outer_diameter_mm',value:110,confirmed_at:'2026-08-10T11:30:00.000Z'}]);expect(edited.annotation!.status).toBe('needs_review')});
});
describe('human field projection',()=>{it('uses production options and readable Russian labels',()=>{const item=reviewRecord(['/attributes/handle_type']).bundle.items[0].catalog_item!,field=buildCatalogEditFields(item)[0];expect(field.options?.map(x=>x.value)).toContain('lever');expect(fieldLabel(field)).toBe('Тип рукоятки');for(const[value,label]of [['adapter','Переходник'],['coupling','Муфта'],['elbow','Угольник'],['tee','Тройник'],['cleanout','Ревизия'],['lever','Рычаг'],['female_thread','Внутренняя резьба']])expect(valueLabel(value)).toBe(label)});it('projects missing_paths without relying on unknown_fields and preserves generic issues as reasons',()=>{const item=reviewRecord([]).bundle.items[0].catalog_item!;item.annotation!.issues=[{code:'MISSING_REQUIRED_EVIDENCE',details:{missing_paths:['/attributes/handle_type']}},{code:'CONTRADICTORY_SOURCE'}];expect(buildCatalogEditFields(item).map(field=>field.jsonPointer)).toEqual(['/attributes/handle_type']);expect(collectUnresolvedReviewPointers(item.annotation!)).toEqual(['/attributes/handle_type']);expect(countUnresolvedReviewReasons(item.annotation!)).toBe(2)})});
