export type CatalogItemStatus='validated'|'needs_review'|'invalid'|'unsupported';
export interface CatalogSourcePosition {sheet?:string;row?:number}
export interface CatalogSource {raw_name?:string;supplier_sku?:string|null;gtin?:unknown;price?:unknown;currency?:unknown;stock_quantity?:unknown;unit?:unknown;context?:unknown;source_position?:CatalogSourcePosition;raw_fields?:Record<string,unknown>;[key:string]:unknown}
export interface CatalogIssue {code?:string;json_pointer?:string;message?:string;details?:unknown}
export interface CatalogAmbiguity {code?:string;json_pointer?:string;source_text?:string;possible_values?:unknown[];blocking?:boolean}
export interface CatalogEvidence {json_pointer?:string;source_text?:string;raw_value?:unknown;source_position?:CatalogSourcePosition}
export interface OperatorConfirmation {json_pointer:string;value:unknown;confirmed_at:string}
export interface CatalogAnnotation {status?:CatalogItemStatus;reason_code?:string;unknown_fields?:string[];issues?:CatalogIssue[];ambiguities?:CatalogAmbiguity[];evidence?:CatalogEvidence[];operator_confirmations?:OperatorConfirmation[]}
export interface CatalogItem {source_item_id?:string;class_id?:string;identity?:Record<string,unknown>;attributes?:Record<string,unknown>;ports?:unknown[];annotation?:CatalogAnnotation;[key:string]:unknown}
export interface CatalogBundle {taxonomy_version:string;catalog:{catalog_id:string;source_file_name:string;source_sha256:string;item_count:number};items:Array<{source?:CatalogSource;catalog_item?:CatalogItem}>;[key:string]:unknown}
export interface CatalogRecord { recordId:string;catalogId:string;sourceFileName:string;sourceSha256:string;taxonomyVersion:string;addedAt:string;updatedAt:string;enabled:boolean;itemCount:number;validatedCount:number;needsReviewCount:number;semanticRevision:number;size:number;bundle:CatalogBundle }
export function normalizeCatalogRecord(record:CatalogRecord):CatalogRecord{return {...record,semanticRevision:record.semanticRevision??0}}
export function getCatalogItemStatusCounts(bundle:CatalogBundle){const counts={total:bundle.items.length,validated:0,needsReview:0,invalid:0,unsupported:0,matchable:0,nonMatchable:0};for(const entry of bundle.items){switch(entry.catalog_item?.annotation?.status){case'validated':counts.validated++;counts.matchable++;break;case'needs_review':counts.needsReview++;counts.matchable++;break;case'invalid':counts.invalid++;counts.nonMatchable++;break;case'unsupported':counts.unsupported++;counts.nonMatchable++;break}}return counts}
export function getCatalogDiagnostics(record:CatalogRecord){const counts=getCatalogItemStatusCounts(record.bundle);return{catalog_id:record.catalogId,source_sha256:record.sourceSha256,summary:{total:counts.total,validated:counts.validated,needs_review:counts.needsReview,invalid:counts.invalid,unsupported:counts.unsupported,non_matchable:counts.nonMatchable},excluded_items:record.bundle.items.flatMap(entry=>{const item=entry.catalog_item,status=item?.annotation?.status;if(status!=='unsupported'&&status!=='invalid')return[];return[{source_item_id:item?.source_item_id,source_reference:entry.source?.raw_name??(entry.source?.source_position?`${entry.source.source_position.sheet??''}:${entry.source.source_position.row??''}`:undefined),status,...(status==='unsupported'?{reason_code:item?.annotation?.reason_code}:{issues:item?.annotation?.issues??[]})}]})}}
export function createCatalogRecord(bundle:CatalogBundle, size=0, now=new Date().toISOString()):CatalogRecord { const counts=getCatalogItemStatusCounts(bundle); return {recordId:crypto.randomUUID(),catalogId:bundle.catalog.catalog_id,sourceFileName:bundle.catalog.source_file_name,sourceSha256:bundle.catalog.source_sha256,taxonomyVersion:bundle.taxonomy_version,addedAt:now,updatedAt:now,enabled:true,itemCount:counts.total,validatedCount:counts.validated,needsReviewCount:counts.needsReview,semanticRevision:0,size,bundle}; }
