import {beforeEach,describe,expect,it,vi} from 'vitest';
import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import taxonomyLight from '../../../../taxonomy/taxonomy-light.json';
import requestBundle from '../../../../tests/fixtures/bundles/request.valid.json';
import {RequestPreparationWorkspace} from './RequestPreparationWorkspace';
import {downloadJsonFile,downloadTextFile} from '../../lib/download-file';

vi.mock('../../lib/download-file',()=>({downloadJsonFile:vi.fn(),downloadTextFile:vi.fn()}));

const source={kind:'request_source',source_file:'request.xlsx',line_count:2,lines:[{line_id:'1',raw_text:'Кран шаровой',quantity_raw:'1'},{line_id:'2',raw_text:'Неизвестная позиция',quantity_raw:null}]};
const routing={kind:'request_routing',schema_version:'1.0.0',taxonomy_version:taxonomyLight.taxonomy_version,source_file:'request.xlsx',line_count:2,routes:[{line_id:'1',decision:'candidates',class_ids:['valve.ball']},{line_id:'2',decision:'unsupported',reason_code:'NO_TAXONOMY_CLASS'}]};
const textFile=(name:string,text:string,type:string)=>Object.assign(new File([text],name,{type}),{text:async()=>text});
const jsonFile=(name:string,value:unknown)=>textFile(name,JSON.stringify(value),'application/json');
const originalFile=(name='request.xlsx')=>new File(['source'],name,{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
const inputFor=(label:string)=>screen.getByText(label).parentElement!.querySelector('input') as HTMLInputElement;

function setup(onBundleReady=vi.fn()) {render(<RequestPreparationWorkspace onBundleReady={onBundleReady}/>);return {user:userEvent.setup(),onBundleReady};}
async function selectOriginal(_user:ReturnType<typeof userEvent.setup>,name='request.xlsx'){fireEvent.change(inputFor('Выберите исходный документ заявки'),{target:{files:[originalFile(name)]}});}
async function importValid(_user:ReturnType<typeof userEvent.setup>,files=[jsonFile('request-source.json',source),jsonFile('request-routing.json',routing)]){fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files}});await screen.findByText('Разметка классов проверена',{selector:'b'});}

beforeEach(()=>vi.clearAllMocks());
describe('RequestPreparationWorkspace',()=>{
  it('enables STEP1 only after selecting original request',async()=>{const {user}=setup();expect(screen.getByRole('button',{name:'Скачать промпт STEP 1'})).toBeDisabled();expect(screen.getByRole('button',{name:'Скачать light taxonomy'})).toBeDisabled();expect(inputFor('Загрузите два JSON из STEP 1')).toBeDisabled();await selectOriginal(user);expect(screen.getByText('request.xlsx',{selector:'b'})).toBeVisible();expect(screen.getByRole('button',{name:'Скачать промпт STEP 1'})).toBeEnabled();expect(screen.getByRole('button',{name:'Скачать light taxonomy'})).toBeEnabled();expect(inputFor('Загрузите два JSON из STEP 1')).toBeEnabled()});
  it('downloads canonical STEP1 assets',async()=>{const {user}=setup();await selectOriginal(user);await user.click(screen.getByRole('button',{name:'Скачать промпт STEP 1'}));expect(downloadTextFile).toHaveBeenCalledWith('REQUEST_PREPARE_PROMPT.md',expect.stringMatching(/.+/),'text/markdown;charset=utf-8');await user.click(screen.getByRole('button',{name:'Скачать light taxonomy'}));expect(downloadJsonFile).toHaveBeenCalledWith('taxonomy-light.json',taxonomyLight)});
  it('accepts valid request-source and request-routing',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user);expect(screen.getByText(/2 строк · 1 классов выбрано · 1 строк вне taxonomy/)).toBeVisible();expect(screen.getByRole('heading',{name:'3. Разметить характеристики заявки'})).toBeVisible()});
  it('accepts STEP1 artifacts in either file order',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user,[jsonFile('routing.json',routing),jsonFile('source.json',source)]);expect(screen.getByRole('heading',{name:'3. Разметить характеристики заявки'})).toBeVisible()});
  it('rejects duplicate STEP1 artifact kind',async()=>{const {user}=setup();await selectOriginal(user);fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files:[jsonFile('source-1.json',source),jsonFile('source-2.json',source),jsonFile('routing.json',routing)]}});expect(await screen.findByRole('status')).toHaveTextContent('Загружены два request-source.json');expect(screen.queryByRole('heading',{name:'3. Разметить характеристики заявки'})).not.toBeInTheDocument()});
  it('rejects unknown STEP1 JSON kind',async()=>{const {user}=setup();await selectOriginal(user);fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files:[jsonFile('unknown.json',{kind:'something_else'})]}});expect(await screen.findByRole('status')).toHaveTextContent('Загружен JSON неизвестного типа');expect(screen.queryByRole('button',{name:'Скачать selected kit'})).not.toBeInTheDocument()});
  it('rejects STEP1 result created for another source file',async()=>{const {user}=setup();await selectOriginal(user);const otherSource={...source,source_file:'another-request.xlsx'},otherRouting={...routing,source_file:'another-request.xlsx'};fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files:[jsonFile('source.json',otherSource),jsonFile('routing.json',otherRouting)]}});expect(await screen.findByRole('status')).toHaveTextContent('request-source создан для другого исходного файла');expect(screen.queryByRole('heading',{name:'3. Разметить характеристики заявки'})).not.toBeInTheDocument()});
  it('downloads the generated selected kit',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user);await user.click(screen.getByRole('button',{name:'Скачать selected kit'}));expect(downloadJsonFile).toHaveBeenCalledWith('request-selected-kit.json',expect.objectContaining({kind:'request_selected_annotation_kit',selected_class_ids:['valve.ball']}))});
  it('requires a new chat for STEP2 and downloads validated source',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user);expect(screen.getByText(/Создайте обязательно новый чат/)).toBeVisible();expect(screen.getByRole('button',{name:'Скачать промпт STEP 2'})).toBeVisible();expect(screen.getByRole('button',{name:'Скачать request-source.json'})).toBeVisible();expect(screen.getByRole('button',{name:'Скачать selected kit'})).toBeVisible();await user.click(screen.getByRole('button',{name:'Скачать request-source.json'}));expect(downloadJsonFile).toHaveBeenCalledWith('request-source.json',source)});
  it('passes a valid final request bundle to onBundleReady',async()=>{const {user,onBundleReady}=setup();const bundleSource={kind:'request_source',source_file:'request.xlsx',line_count:1,lines:[{line_id:requestBundle.request_document.lines[0].line_id,raw_text:requestBundle.request_document.lines[0].raw_text,quantity_raw:'10 шт'}]},bundleRouting={...routing,line_count:1,routes:[{line_id:requestBundle.request_document.lines[0].line_id,decision:'candidates',class_ids:['valve.ball']}]};await selectOriginal(user);await importValid(user,[jsonFile('source.json',bundleSource),jsonFile('routing.json',bundleRouting)]);fireEvent.change(inputFor('Загрузите request_bundle.json из STEP 2'),{target:{files:[jsonFile('request_bundle.json',requestBundle)]}});await waitFor(()=>expect(onBundleReady).toHaveBeenCalledWith(requestBundle,'request_bundle.json'));expect(onBundleReady).toHaveBeenCalledTimes(1)});
  it('rejects a valid request bundle from another request',async()=>{const {user,onBundleReady}=setup();await selectOriginal(user);await importValid(user);fireEvent.change(inputFor('Загрузите request_bundle.json из STEP 2'),{target:{files:[jsonFile('request_bundle.json',requestBundle)]}});await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Финальный JSON относится к другой заявке'));expect(onBundleReady).not.toHaveBeenCalled()});
  it('keeps previously valid STEP1 preparation after invalid replacement',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user);fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files:[textFile('bad.json','{bad json','application/json')]}});expect(await screen.findByRole('status')).toHaveTextContent('Предыдущий корректный результат сохранён');expect(screen.getByText(/2 строк · 1 классов выбрано · 1 строк вне taxonomy/)).toBeVisible();expect(screen.getByRole('heading',{name:'3. Разметить характеристики заявки'})).toBeVisible()});
  it('changing original source clears previous preparation',async()=>{const {user}=setup();await selectOriginal(user);await importValid(user);await selectOriginal(user,'request-b.xlsx');expect(screen.getByText('request-b.xlsx',{selector:'b'})).toBeVisible();expect(screen.queryByRole('heading',{name:'3. Разметить характеристики заявки'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Скачать selected kit'})).not.toBeInTheDocument()});
  it('rejects malformed STEP1 JSON without crashing',async()=>{const {user}=setup();await selectOriginal(user);fireEvent.change(inputFor('Загрузите два JSON из STEP 1'),{target:{files:[textFile('bad.json','{bad json','application/json')]}});expect(await screen.findByRole('status')).toHaveTextContent('содержит некорректный JSON');expect(screen.getByRole('heading',{name:'2. Определить классы товаров'})).toBeVisible()});
});
