import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { readFile } from 'node:fs/promises';
import { canonical, sha256 } from './review-pack-builder.mjs';
export const classDecision = class_id => ({class_id,decision:null,final_class_ids:[],approved_attributes:[],approved_ports:[],approved_value_set_refs:[],matching_critical_fields:[],notes:null});
export const caseDecision = case_id => ({case_id,decision:null,selected_option_ids:[],notes:null});
export function createDraft(pack) { return {approval_schema_version:'1.0.0',proposal_version:pack.proposal_version,source_inventory_sha256:pack.source_inventory_sha256,proposal_sha256:pack.proposal_sha256,status:'draft',mass_annotation_allowed:false,class_decisions:pack.classes.map(x=>classDecision(x.class_id)),case_decisions:pack.unresolved_cases.map(x=>caseDecision(x.case_id)),owner_signoff:null}; }
function exactSet(items, key, expected, label, errors) { const ids=items.map(x=>x[key]); for(const id of new Set(ids)) if(ids.filter(x=>x===id).length!==1) errors.push(`duplicate ${label} ID: ${id}`); for(const id of ids) if(!expected.has(id)) errors.push(`unknown ${label} ID: ${id}`); for(const id of expected) if(!ids.includes(id)) errors.push(`missing ${label} ID: ${id}`); }
export async function validateApproval(approval, pack, schemaPath='schemas/taxonomy/taxonomy-approval.schema.json') {
 const errors=[]; const schema=JSON.parse(await readFile(schemaPath,'utf8')); const ajv=new Ajv2020({allErrors:true,strict:false}); addFormats(ajv); const validate=ajv.compile(schema); if(!validate(approval)) errors.push(...(validate.errors??[]).map(e=>`schema ${e.instancePath || '/'} ${e.message}`));
 if(approval.source_inventory_sha256!==pack.source_inventory_sha256) errors.push('stale source_inventory_sha256'); if(approval.proposal_sha256!==pack.proposal_sha256) errors.push('stale proposal_sha256');
 exactSet(approval.class_decisions??[],'class_id',new Set(pack.classes.map(x=>x.class_id)),'class',errors); exactSet(approval.case_decisions??[],'case_id',new Set(pack.unresolved_cases.map(x=>x.case_id)),'case',errors);
 for(const d of approval.class_decisions??[]) { const n=d.final_class_ids?.length??0; if(d.decision==='approve'&&n!==1) errors.push(`${d.class_id}: approve requires exactly one final_class_id`); if(d.decision==='revise'&&(n!==1||!d.notes?.trim())) errors.push(`${d.class_id}: revise requires one final_class_id and notes`); if(d.decision==='reject'&&n) errors.push(`${d.class_id}: reject requires empty final_class_ids`); if(d.decision==='split'&&n<2) errors.push(`${d.class_id}: split requires at least two final_class_ids`); if(d.decision==='merge'&&(n!==1||d.final_class_ids[0]===d.class_id)) errors.push(`${d.class_id}: merge requires one different final_class_id`); }
 for(const d of approval.case_decisions??[]) { const selected=d.selected_option_ids??[]; const n=selected.length; if(d.decision==='select_option'){if(!n) errors.push(`${d.case_id}: select_option requires selected_option_ids`); const candidates=new Set(pack.unresolved_cases.find(x=>x.case_id===d.case_id)?.candidate_options??[]); for(const id of selected) if(!candidates.has(id)) errors.push(`${d.case_id}: unknown selected option ID: ${id}`);} if(d.decision==='create_new_class'&&n!==1) errors.push(`${d.case_id}: create_new_class requires one class ID`); if(d.decision && !['select_option','create_new_class'].includes(d.decision) && n) errors.push(`${d.case_id}: ${d.decision} requires empty selected_option_ids`); }
 if(approval.status==='approved') { if((approval.class_decisions??[]).some(x=>x.decision===null)) errors.push('approved status requires all class decisions'); if((approval.case_decisions??[]).some(x=>x.decision===null)) errors.push('approved status requires all case decisions'); if((approval.case_decisions??[]).some(x=>x.decision==='defer')) errors.push('approved status forbids defer'); if(!approval.owner_signoff) errors.push('approved status requires owner_signoff'); }
 if(approval.owner_signoff?.proposal_sha256!==undefined && approval.owner_signoff.proposal_sha256!==approval.proposal_sha256) errors.push('owner_signoff proposal_sha256 mismatch');
 const forbidden=/(raw_name|source_item_id|supplier_sku|gtin|price|cost|discount|manufacturer.?article)/i; const walk=(v,path='')=>{if(Array.isArray(v))v.forEach((x,i)=>walk(x,`${path}/${i}`));else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v)){if(forbidden.test(k))errors.push(`forbidden product field: ${path}/${k}`);walk(x,`${path}/${k}`)}}; walk(approval);
 return errors;
}
export function proposalHash(taxonomy){return sha256(canonical(taxonomy));}
